repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-toml
      - id: debug-statements

  - repo: local
    hooks:
      - id: black
        name: black
        entry: pdm
        language: system
        args: [run, black]
        types: [python]

      - id: flake8
        name: flake8
        entry: pdm
        language: system
        args: [run, lint]
        types: [python]
        pass_filenames: false

      - id: isort
        name: isort
        entry: pdm
        language: system
        args: [run, isort]
        types: [python]

      - id: mypy
        name: mypy
        entry: pdm
        language: system
        args: [run, typecheck]
        types: [python]
        pass_filenames: false

      - id: bandit
        name: bandit
        entry: pdm
        language: system
        args: [run, security-precommit]
        pass_filenames: false

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.13.0
    hooks:
      - id: commitizen
        stages: [commit-msg]
